language: bash

addons:
  apt:
    packages:
    - lua5.1
    - luarocks
  
install:
  - eval $(luarocks path --bin)
  - luarocks install --local lua-cjson
  - luarocks install --local busted

script:
  - bash tests/validate_site.sh
